/**
 * Confirmation literals required by the daemon's approval-gated POST routes.
 *
 * Single source of truth shared by the daemon (zod schemas), the MCP bridge, and Studio, so the
 * three definitions can never drift apart (docs/audit-2026-08-31.md, Q5 / §6.3-4).
 */
export const CONFIRMATIONS = {
  REVISE_BLUEPRINT: 'REVISE_BLUEPRINT',
  APPROVE_BASELINE: 'APPROVE_BASELINE',
  APPLY_BASELINE: 'APPLY_BASELINE',
  RETRY_APPLY: 'RETRY_APPLY',
  RECOVER_WORKSPACE: 'RECOVER_WORKSPACE',
  RUN_QUALITY_GATE: 'RUN_QUALITY_GATE',
  INSTALL_DEPENDENCIES: 'INSTALL_DEPENDENCIES',
  APPROVE_FEATURE_TASK: 'APPROVE_FEATURE_TASK',
  PREPARE_RUNTIME_RUN: 'PREPARE_RUNTIME_RUN',
  EXECUTE_RUNTIME_RUN: 'EXECUTE_RUNTIME_RUN',
  RETRY_RUNTIME_RUN: 'RETRY_RUNTIME_RUN',
  CANCEL_RUNTIME_RUN: 'CANCEL_RUNTIME_RUN',
  OPEN_PULL_REQUEST: 'OPEN_PULL_REQUEST',
  RECORD_PR_EVIDENCE: 'RECORD_PR_EVIDENCE',
  RECORD_PREVIEW_EVIDENCE: 'RECORD_PREVIEW_EVIDENCE',
  DEPLOY_PREVIEW: 'DEPLOY_PREVIEW',
  CLEANUP_PREVIEW: 'CLEANUP_PREVIEW',
  APPLY_FAKE_PROVIDERS: 'APPLY_FAKE_PROVIDERS',
  APPLY_REAL_PROVIDERS: 'APPLY_REAL_PROVIDERS',
  APPROVE_DELIVERY: 'APPROVE_DELIVERY',
  REQUEST_RELEASE: 'REQUEST_RELEASE',
  APPROVE_RELEASE: 'APPROVE_RELEASE',
  RETRY_RELEASE: 'RETRY_RELEASE',
} as const;

export type ConfirmationLiteral = (typeof CONFIRMATIONS)[keyof typeof CONFIRMATIONS];
