import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Credentials } from './credentials.js';
import type { ProjectResources } from './project-resources.js';

export function generateEnvFile(workspacePath: string, credentials: Credentials, resources: ProjectResources | null, appName: string) {
  const lines = ['# Generated by Agent-Dev. Do not commit this file.', `APP_NAME=${appName}`, 'NODE_ENV=development'];
  if (resources) for (const [provider, values] of Object.entries(resources.providers)) for (const [key, value] of Object.entries(values)) {
    if (typeof value !== 'string' || /key|token|secret|password|database|connection/i.test(key)) continue;
    lines.push(`${provider.toUpperCase()}_${key.replace(/([a-z])([A-Z])/g, '$1_$2').toUpperCase()}=${value}`);
  }
  for (const [key, value] of Object.entries(credentials)) if (!['GITHUB_TOKEN', 'VERCEL_TOKEN', 'CLOUDFLARE_API_TOKEN', 'SUPABASE_ACCESS_TOKEN'].includes(key)) lines.push(`${key}=${value}`);
  writeFileSync(join(workspacePath, '.env'), `${lines.join('\n')}\n`, { mode: 0o600 });
}
